title: CodeFaults's Blog
email: codefault@163.com
baseurl: ""
url: ""

github_username:  codefaults

theme: minima
plugins:
  - jekyll-feed

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed